wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1697772529.54052
    t:
      1:
      - 1
      - 5
      - 8
      - 41
      - 53
      - 54
      - 55
      2:
      - 1
      - 5
      - 8
      - 41
      - 53
      - 54
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.9.13
      5: 0.13.4
      8:
      - 1
      - 3
      - 5
epochs:
  desc: null
  value: 3
learning_rate:
  desc: null
  value: 0.01
